FROM node:20-alpine
# Installing libvips-dev for sharp Compatibility
RUN apk update  \
    && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git openssh \
    && mkdir -p -m 0700 ~/.ssh  \
    && ssh-keyscan github.com >> ~/.ssh/known_hosts
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/
COPY package.json yarn.lock ./
RUN --mount=type=ssh \
    yarn config set network-timeout 600000 -g \
    && yarn install -f
#WORKDIR /opt/node_modules/@notum-cz/strapi-plugin-location
#RUN npm run build

WORKDIR /opt/app
COPY . .
ENV PATH /opt/node_modules/.bin:$PATH
RUN chown -R node:node /opt/app
USER node
RUN  --mount=type=ssh ["yarn", "build"]
EXPOSE 1337
CMD ["yarn", "develop"]
