version: '3'
services:
  wittensee-history-sqladmin:
    container_name: wittensee-history-sqladmin
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=wittensee-history-db
    networks:
      - wittensee-history
    depends_on:
      - wittensee-history-db

networks:
  wittensee-history:
    driver: bridge
